//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public System.DateTime Dest_Date { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int EventId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual User User { get; set; }
    }
}
